export const GET_TODOS_REQUEST = "GET_TODOS_REQUEST";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_FAILURE = "GET_TODOS_FAILURE";

export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE";

export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_FAILURE = "DELETE_TODO_FAILURE";

export const DONE_TODO_REQUEST = "DONE_TODO_REQUEST";
export const DONE_TODO_SUCCESS = "DONE_TODO_SUCCESS";
export const DONE_TODO_FAILURE = "DONE_TODO_FAILURE";

export const IMPORTANT_TODO_REQUEST = "IMPORTANT_TODO_REQUEST";
export const IMPORTANT_TODO_SUCCESS = "IMPORTANT_TODO_SUCCESS";
export const IMPORTANT_TODO_FAILURE = "IMPORTANT_TODO_FAILURE";